# Generated by Django 5.0.4 on 2024-05-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='air_humidity',
            field=models.FloatField(default=0.0),
        ),
    ]
