# Generated by Django 5.0.4 on 2024-04-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sensordata_sensor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='sensor_id',
            new_name='sensor_data_id',
        ),
    ]
